version: '2'

services:
  minio:
    image: minio/minio
    container_name: minio
    ports:
      - 9000:9000
    environment:
      - MINIO_ACCESS_KEY=Q3AM3UQ867SPQQA43P2F
      - MINIO_SECRET_KEY=zuf+tfteSlswRu7BJ86wekitnifILbZam1KYY3TG
      - MINIO_REGION=us-east-1
      - MINIO_DOMAIN=localhost
    command: server /export
    volumes:
      - ./config:/root/.minio
      - ./data:/data
    networks:
      - bridge
      
  mc:
    image: minio/mc
    depends_on:
      - minio
    container_name: mc
    environment:
      - MINIO_ACCESS_KEY=Q3AM3UQ867SPQQA43P2F
      - MINIO_SECRET_KEY=zuf+tfteSlswRu7BJ86wekitnifILbZam1KYY3TG
    entrypoint: >
      /bin/sh -c "
      until (/usr/bin/mc config host add s3 http://change-to-your-domain.com:9000 $${MINIO_ACCESS_KEY} $${MINIO_SECRET_KEY}) do echo '...waiting...' && sleep 1; done;
      /usr/bin/mc mb s3/name-of-bucket --region us-east-1;
      /usr/bin/mc policy set public s3/name-of-bucket;
      exit 0;
      "
    networks:
      - bridge

networks:
  bridge:
